### ISSUE TITLE
Not a WAVE file - no WAVE header

### ISSUE THREAD

**Issue by vipermetcaff** [jwallet/spy-spotify#224] opened 2020-04-30 23:40 UTC
#Error Report

**Application**: Spytify  
**Version**:     1.6.0.0  
**Region**:        
**Date**: 4/30/2020  
**Time**: 11:37 PM  

**Error Message**: Not a WAVE file - no WAVE header
 
##Stack Traces
```text
Top-level Exception
Type:    System.FormatException
Message: Not a WAVE file - no WAVE header
Source:  NAudio
Stack Trace: at NAudio.FileFormats.Wav.WaveFileChunkReader.ReadWaveHeader(Stream stream)
   at NAudio.Wave.WaveFileReader..ctor(Stream inputStream, Boolean ownInput)
   at EspionSpotify.Recorder.&lt;WriteStreamOutputToFileBasedOnNumberOfChannels&gt;d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EspionSpotify.Recorder.&lt;WaveIn_RecordingStopped&gt;d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
 
```
 
##Assembly References
 - ExceptionReporter.NET, Version=4.0.2.0  
 - MetroFramework, Version=1.4.0.0  
 - mscorlib, Version=4.0.0.0  
 - NAudio, Version=1.9.0.0  
 - NAudio.Lame, Version=1.0.9.26885  
 - Newtonsoft.Json, Version=12.0.0.0  
 - PCLWebUtility, Version=1.0.0.0  
 - SpotifyAPI.Web, Version=1.0.0.0  
 - SpotifyAPI.Web.Auth, Version=1.0.0.0  
 - Spytify, Version=1.6.0.0  
 - System, Version=4.0.0.0  
 - System.Core, Version=4.0.0.0  
 - System.Drawing, Version=4.0.0.0  
 - System.IO.Abstractions, Version=7.0.0.0  
 - System.Net.Http, Version=4.0.0.0  
 - System.Windows.Forms, Version=4.0.0.0  
 - System.Xml, Version=4.0.0.0  
 - taglib-sharp, Version=2.1.0.0  

##System Info  
```test
Operating System
-Microsoft Windows 10 Pro
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = -360
--FreePhysicalMemory = 12562464
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.18362

Machine
-VIPERSPC
--Manufacturer = System manufacturer
--Model = System Product Name
--TotalPhysicalMemory = 17116495872


```

**Comment by jwallet** [comment] 2020-05-01 01:58
hi there thanks for reporting the issue
- does it happens once or for every recordings
- do you see a file added to the list in the `local/temp/` folder in explorer, when ordered by `date modified` to `most recents` ?

> Type in Explorer path: `%APPDATA%`, back of one folder and go to `/Local/Temp/`

![image](https://user-images.githubusercontent.com/23088305/80775428-93f02700-8b2d-11ea-9b5e-71325b615f45.png)

**Comment by vipermetcaff** [comment] 2020-05-01 06:22
> %APPDATA%
its been happening on every recording
yes its showing the temp files in /local/temp

**Comment by rock6663** [comment] 2020-05-01 10:52
> > %APPDATA%
> > its been happening on every recording
> > yes its showing the temp files in /local/temp
> > i got it working

can you explain the solution i have same issue

**Comment by jwallet** [comment] 2020-05-01 11:13
you have to give access to spytify to write in temp data, normally any app can do.
Here are some stuff to try:
- make sure you don't run the app in the zip file, unzip it somewhere like your User/Desktop
- run the app as an admin
- try to move the app folder to C:\ drive root (normally the app will have more rights after the move)

You should see a file being added to the most recents file in
> `YOUR_USER\AppData\Local\Temp\`

![h](https://user-images.githubusercontent.com/23088305/80801697-3256a980-8b7b-11ea-94d1-35b8a9c20323.gif)

**Comment by rock6663** [comment] 2020-05-01 14:22
> you have to give access to spytify to write in temp data, normally any app can do.
> Here are some stuff to try:
> 
> * make sure you don't run the app in the zip file, unzip it somewhere like your User/Desktop
> * run the app as an admin
> * this app has no certificate, so antivirus might block it from executing, make sure it is whitelisted
> * try to move the app folder to `C:\` drive root (normally the app will have more rights after the move)
> 
> You should see a `.tmp` file being added to the most recents file in
> `YOUR_USER\AppData\Local\Temp\`
> 
> ![h](https://user-images.githubusercontent.com/23088305/80801697-3256a980-8b7b-11ea-94d1-35b8a9c20323.gif)
> 
> @vipermetcaff @rock6663 let me know what worked so I can prevent this in the future

@jwallet i tried these it worked but i realised something it works but only when i dont do anything (surfing the web chatting from dc etc.) on pc. when i start to do something it gives same error again

**Comment by jwallet** [comment] 2020-05-01 15:26
is it because another app is requesting the sound card, maybe set the audio device as `Virtual Audio Device` and output Spotify to the same one ?

**Comment by WVLFI** [comment] 2020-05-03 15:35
Just a little heads up,
Doing EXACTLY what @jwallet says fixes the issue. At first I was concerned it had something to do with me using the LastFM API but turns out it wasn't the issue.
As for @rock6663 saying that it happens only when he browses or does anything, for some reason that doesn't apply to me.

A little few pointers (from my problems) to help debugging the code is this:
- Only happens when the song ends and changes to another one
- Using LastFM API
- Not running on adm
- Not on local disc C
- Using computer as usual, was not afk

Thanks for helping @jwallet , you're the best!
-WVLFI

**Comment by WVLFI** [comment] 2020-05-03 15:44
Having same issue here, tried everything you suggested @jwallet 
Unlike @rock6663 even if I don't use my computer the error still persists.
Something I would like to point out is that I am using the 'LastFM' API because the 'Spotify' API is not available for me to select (grayed out).
Hope you can fix the issue soon.

**Comment by vipermetcaff** [comment] 2020-05-03 18:15
still doing it to me

**Comment by jwallet** [comment] 2020-05-04 01:57
#### comment for devs:
[Recorder.cs#L119](https://github.com/jwallet/spy-spotify/blob/master/EspionSpotify/Recorder.cs#L119)
new NAudio.WaveFileReader(_tempFile) look like it can't open the file because it is still locked, some report that they solve the issue using System Stream instead

**Comment by WVLFI** [comment] 2020-05-04 02:53
Any suggestions on how do do that? the system stream. Not too familiar with that

**Comment by jwallet** [comment] 2020-05-04 14:39
if this happens for anyone, I will like to see the actual console logs, screenshots of settings you use, upload here the `.tmp` files that you have, like shown above related to spytify apps (order by date - recents) and the song used that failed to save to mp3 open.spotify.com/search. My guess at the moment is a third party app that keep spytify from writing on the disk like anti-malware, anti-virus, looks like this issue does not hit all 3,000 ish users online right now.

**Comment by WVLFI** [comment] 2020-05-05 01:09
Hey @jwallet , just wanted to let you know that this only affects my laptop, has no effects on my pc. my pc is more updated and kept away from apps that look shady, and the pc is using the latest windows updates.
Both pc and laptop have default windows defender installed and do not have any third party anti virus installed. 
Thought this might help.

**Comment by I-Have-Bugs** [comment] 2020-05-06 13:41
Same thing is happening to me.

**Comment by I-Have-Bugs** [comment] 2020-05-06 13:44
#Error Report

**Application**: Spytify  
**Version**:     1.6.0.0  
**Region**:        
**Date**: 06/05/2020  
**Time**: 1:43 PM  

**Error Message**: Not a WAVE file - no WAVE header
 
##Stack Traces
```text
Top-level Exception
Type:    System.FormatException
Message: Not a WAVE file - no WAVE header
Source:  NAudio
Stack Trace: at NAudio.FileFormats.Wav.WaveFileChunkReader.ReadWaveHeader(Stream stream)
   at NAudio.Wave.WaveFileReader..ctor(Stream inputStream, Boolean ownInput)
   at EspionSpotify.Recorder.&lt;WriteStreamOutputToFileBasedOnNumberOfChannels&gt;d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EspionSpotify.Recorder.&lt;WaveIn_RecordingStopped&gt;d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
 
```
 
##Assembly References
 - ExceptionReporter.NET, Version=4.0.2.0  
 - MetroFramework, Version=1.4.0.0  
 - mscorlib, Version=4.0.0.0  
 - NAudio, Version=1.9.0.0  
 - NAudio.Lame, Version=1.0.9.26885  
 - Newtonsoft.Json, Version=12.0.0.0  
 - PCLWebUtility, Version=1.0.0.0  
 - SpotifyAPI.Web, Version=1.0.0.0  
 - SpotifyAPI.Web.Auth, Version=1.0.0.0  
 - Spytify, Version=1.6.0.0  
 - System, Version=4.0.0.0  
 - System.Core, Version=4.0.0.0  
 - System.Drawing, Version=4.0.0.0  
 - System.IO.Abstractions, Version=7.0.0.0  
 - System.Net.Http, Version=4.0.0.0  
 - System.Windows.Forms, Version=4.0.0.0  
 - System.Xml, Version=4.0.0.0  
 - taglib-sharp, Version=2.1.0.0  

##System Info  
```test
Operating System
-Microsoft Windows 7 Professional
--CodeSet = 936
--CSDVersion = Service Pack 1
--CurrentTimeZone = -240
--FreePhysicalMemory = 3938324
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 1
--ServicePackMinorVersion = 0
--Version = 6.1.7601

Machine
-TONY-PC
--Manufacturer = ASUSTeK COMPUTER INC.
--Model = BM2AD_D310312510MT_ED3
--TotalPhysicalMemory = 8456921088


```

**Comment by I-Have-Bugs** [comment] 2020-05-06 13:44
I also don't think this is an issue with Spytify, it is happening on other programs in Windows

**Comment by I-Have-Bugs** [comment] 2020-05-06 13:47
I think the error literally states that it expected a WAVE file but got an mp3 file. I'm currently using the WAVE file export function and it's working

**Comment by I-Have-Bugs** [comment] 2020-05-06 13:50
Yup it's confirmed you just need to select the WAVE file export. I don't program much so I can't fix the issue but I hope that the dev can fix it soon

**Comment by I-Have-Bugs** [comment] 2020-05-06 13:59
Basically you can:
1. Change the export to a WAV file (worked for me)
2. Go to sound in the control panel, then to recording then right click and click view disabled then if a new one pops up then right click, select properties and in the very bottom drop down menu select, use this device
3. Try using a fresh install
4. Disable your anti-virus
5. Don't run anything else and check if it works

**Comment by I-Have-Bugs** [comment] 2020-05-06 14:25
After selecting WAV and closing it then reopening it, it will show that you've selected WAV but it still selected MP3 by default so you need to click on mp3 then click on WAV again to make sure it's WAV if the error still shows, this is a bug again

**Comment by jwallet** [comment] 2020-05-06 15:29
selecting wav format does not execute the same code at all, that's why it is working

**Comment by vipermetcaff** [comment] 2020-05-06 17:56
im useing an older version of spytify v1.2 with the vb audio Calbe and it works Great Havent Had Any Errors

**Comment by I-Have-Bugs** [comment] 2020-05-06 18:44
> 
> 
> im using an older version of spytify v1.2 with the vb audio Calbe and it works Great Havent Had Any Errors

Could you send the source code to me?

**Comment by jwallet** [comment] 2020-05-06 23:11
subscribe to this thread for those who have the issue, I'm gonna release here the debug version to see what could fix it. I can't reproduce the issue myself.
![image](https://user-images.githubusercontent.com/23088305/81237316-5a0b9e80-8fcd-11ea-9268-e25ab3d7b9f8.png)

**Comment by jwallet** [comment] 2020-05-07 00:09
[spytify-audio-writer.zip](https://github.com/jwallet/spy-spotify/files/4590047/spytify-audio-writer.zip)

**Comment by niknak101** [comment] 2020-05-07 02:49
Hi jwallet, first thanks for your work on this app. I'll contribute with a translation soon.

I'm receiving the same WAVE header error message.
- Windows 10 Pro, up to date
- F-Secure AV (no false positives received while using the app)
- Spotify Premium
- using an external USB Focusrite Scarlett audio interface (haven't installed the VB virtual cable driver)
- Running app as administrator, on a path with no spaces just in case.
- Version 1.5 was working without issues, but I heard pops & clicks on the recordings.

I tried just now using the "spytify-audio-writer" debug version you posted above, and receive the following error message on the log (output path has been blurred):

> Error while recording: Unknown exception: tempFile used: F:\Users\username\AppData\Local\Temp\tmp84F9.tmp, track used: Zhavia Ward - All I Am, The byte stream type of the given URL is unsupported. (Exception from HRESULT: 0xC00D36C4)

![image](https://user-images.githubusercontent.com/64940697/81248414-ac12eb00-8ff2-11ea-90fb-159caebc83f0.png)

![image](https://user-images.githubusercontent.com/64940697/81248896-d022fc00-8ff3-11ea-9fa2-d8f9afffbc27.png)


Instead of a TEMP file, a failed MP3 output was created in the output folder. See attachment.

[output.zip](https://github.com/jwallet/spy-spotify/files/4590416/output.zip)

**Comment by jwallet** [comment] 2020-05-07 04:16
another one here:
[spytify-reset-position-without-flush.zip](https://github.com/jwallet/spy-spotify/files/4590675/spytify-reset-position-without-flush.zip)

**Comment by niknak101** [comment] 2020-05-07 09:44
This latest one (spytify-reset-position-without-flush.zip) is working fine for me. Managed to record about 10 songs without error messages, using the same settings as my previous post.

Offtopic: I finished the spanish translation for future versions.

**Comment by I-Have-Bugs** [comment] 2020-05-07 13:45
I lied, apparently selecting wav still gets the error. I don't know how but it seems random, I managed to get about 20 songs before it crashed

**Comment by Sessionz81** [comment] 2020-05-09 13:33
> it should log the error into the console
> 
> [spytify-audio-writer.zip](https://github.com/jwallet/spy-spotify/files/4590087/spytify-audio-writer.zip)

Hi, I'm not a programmer so have no idea what half of this thread means but I signed up to let you know this link fixed the described problem for me, thank you. I will make sure to donate.

**Comment by SpookyPootis** [comment] 2020-05-09 13:59
> I made a PR that applies [#224 (comment)](https://github.com/jwallet/spy-spotify/issues/224#issuecomment-625019343)
> If you guys here confirm that this is the one that fix the issue you are having I will release a patch
> @I-Have-Bugs @vipermetcaff @rock6663

Just as the user above, I signed up to say thanks! This fixed the no header issue for me. Just dropped it into C: drive and that's it, no antivirus exception or any other modification. Ill keep updated, thanks a lot.

**Comment by jwallet** [comment] 2020-05-09 21:54
Ok then I will release a patch and some other features that were in the pipes

**Closed** 2020-05-10 13:27 UTC
Labels: bug 🐞, naudio 🔊, needs feedback 📬
