### ISSUE TITLE
Feature request: skip already recorded songs by simulating a key press

### ISSUE THREAD

**Issue by deckenventilator24** [jwallet/spy-spotify#254] opened 2020-07-13 17:50 UTC
I would like that spytify skips already recorded songs by simulating the key press of a multimedia key. That would be usefull because you can record more songs in a certain time without waiting for already recorded ones to end playback.
Would be very nice if you add it.

Thanks

**Comment by jwallet** [comment] 2020-08-12 23:15
duplicate of #154

**Closed** 2020-08-12 23:15 UTC
Labels: duplicate 👥, feature ✨
