### ISSUE TITLE
Spy Records Too Hot (Loud)

### ISSUE THREAD

**Issue by mclederp** [jwallet/spy-spotify#274] opened 2020-11-13 11:52 UTC
How do I turn down the level on the recording? Spy records audio too loud.

**What is the bug ?**
After loading the recorded MP3 into editing software like Pro Tools, Cubase, Audacity, etc, the playback clips and distorts with peaks sometimes as high as +2.2dB for some songs. MP3s recorded too loud can cause notable distortion when played through certain playback drivers.

Turning down the Audio Device volume does nothing. Turning down the volume on Spotify does nothing.

Normalization is OFF on Spotify but one of the touted Spy features is normalization. I do not see normalization anywhere in the settings. If there is extra normalization being applied to the recording, is there a way to turn it off or at least adjust it? I do not want any normalization on the audio.

**Track used**
https://open.spotify.com/track/4RZga1rWE9dj5H6oFBaLP4?si=GvOV8_2aQ9OBPX--OFl0bQ

**Comment by laurens94** [comment] 2020-11-17 09:48
I encounter the opposite effect: recorded tracks are too silent. It seems as if the volume percentage gets automatically turned down after using spytify for a while, is that possible?

**Comment by jwallet** [comment] 2020-11-17 12:40
might be related to your audio device selection, did you try adding and using the audio virtual cable provided with the app ?

**Comment by laurens94** [comment] 2020-11-17 16:49
The percentage problem is caused by turning off my screen. When recording I had the volume set to 100%. Then I turned off my screen, which changed the volume to 36%. This also happens when using the audio virtual cable driver.

**Comment by jwallet** [comment] 2020-11-24 02:30
does this happen without spytify running, looks like you have another software running in the background

**Comment by jwallet** [comment] 2020-11-24 02:33
if you lock your pc or put your pc to sleep, spotify will try to reach the next Online device, so if your pc is in sleep mode and then you go on your cellphone or say Hey Google play this thing.. Spotify will then move your session to your new device. So when coming back on your PC you might have your Spotify volume reset

**Comment by laurens94** [comment] 2020-11-24 12:20
For me it's not happening anymore! I don't know what changed it. The pc didn't go into sleep or anything, it was just the display monitor that was turned off/on again.  Thanks anyway

**Comment by MichaelPeter** [comment] 2020-12-13 23:20
I have a differnt problem now (previously not) that if in windows the volume setting is not 100% the loudness is also more silent.
So if volume is just 42% the recorded loudness is just 42%.

Not sure if a new spytify version is responsible or the new spotify version.
Spytify Exe has Version 1.7.0.0

**Comment by jwallet** [comment] 2020-12-27 03:06
The only think spytify does is it set spotify and spytify to 100% in your windows volume mixer 
![image](https://user-images.githubusercontent.com/23088305/103163025-4f08b700-47c6-11eb-98e8-6a3e286b6c06.png)
mutes other apps (see mozilla being set at ~50% of total volume, my headphones are set to 40% but the recordings will always be 100% (so original volume from the stream), if you still have trouble I suggest switching to another audio device

**Comment by R-W-C** [comment] 2020-12-27 22:21
A possible solution for some of you?

Okay, I might be totally wrong, but I what I think is happening to most users is that they use ONE output device, typically the one they always use. I guess most users are not aware that they could and maybe should use a different output device for Spotify and Spytify. Because if you change the volume of your output device, it influences the recording. Just use a separate device for Spotify and Spytify, but how to do this? I am not an expert on this subject, but I do have a solution which works for me, and maybe/probably works for others to. (Maybe the creator of Spytify an explain a little bit more about this subject.)    

Voicemeeter 

I use a brilliant tool called VoiceMeeter (donationware, see https://vb-audio.com/Voicemeeter). What it does it creates an extra (virtual) output device. (I think you can also use a "virtual cable" as output device. I do not know how that works. Probably more or less the same.)
After installing it, you should tell Windows that both Spotify and Spytify have to use VoiceMeeter as output device. Do not change your default audio device.
There is another huge advantage using a separate audio device. As you know, Spytify needs the output to be in stereo. You do not have to change the output from your default audio device from multichannel to stereo and back anymore, if you normally use multichannel output (5.1, 6.1 or 7.1)!

There are a few videos on YouTube on how to setup and use VoiceMeeter 
(ie. https://www.youtube.com/watch?v=j_fk5SqktJg )

VoiceMeeter starting guide (for dummies):
 
Download and install VoiceMeeter.
Start the Spotify desktop application (if it is not running yet): 
Start Spytify application (if it is not running yet). Do not start spying (yet) : 
Right click the speaker icon in the taskbar and select Sound Settings.
Under "Advanced sound options" you can find "App volume and device preferences"
Search for Spotify and change it's output device to "Voicemeeter Input". 
Search for Spytify and change it's output device to "Voicemeeter Input".

If you cannot find Spytify, you can change it's output device in Spytify itself. Go to menu Settings and select "Voicemeeter Input" as audio device. 

If you now play something in Spotify, you will hear nothing. This is a good thing, because your default output device is not VoiceMeeter,. but whatever it was before. 

Okay let's test if it works. Start spying with  Spytify  and play a song in Spotify. After it has finished, goto the saved file and play it with your preferred audio player. It should play just fine.

Play around with VoiceMeeter. Leave it's volume level to 100 and you should be fine (I guess, it works for me).

"But in this way I cannot listen to Spotify." you might says/think. Of course you can, just switch your output device temporary to  "VoiceMeeter Input". That should do the trick.   

Play around with it. It is such a cool tool (and make a little donation, if you think it is useful). 
  
Totally off topic, "speaker fill":

AudioMeeter is a brilliant tool. I actually used it for something totally different: "speaker fill" which is not supported by the audio driver of my Intel NUC mini pc. 
With "Speaker fill", you can send 2.1 audio to all your speakers, not only the front speakers.  My problem was that I did not hear audio over all my speakers when playing audio or video in any browser (Youtube) or playing music in Spotify.

Normally you can enable "Audio fill" like this: 
Press Windows key + R and type “mmsys. 
Go to the Playback tab, select your 5.1 surround speakers and click on Properties.
In Speaker Properties, go to the Enhancement tab and there should be a setting "Speaker fill" (or similar). This should be enabled.

In my case there is no such setting. It is not implemented in my audio driver.

AudioMeeter is a seperate audio driver (which sends audio to my surround receiver), which does support speaker fill. In the GUI of AudioMeeter, on the right side, enable "Stereo Repeat" (both buttons). Sweet!

**Comment by jwallet** [comment] 2020-12-28 00:10
Hey there, thanks for this post I think it will help others, I just wanted to point a few things.

> Because if you change the volume of your output device, it influences the recording. Just use a separate device for Spotify and Spytify

Using the volume slider should not affects the recordings, only if you change Spotify in-app volume. So even if you use your main audio device at 0% or 40% it should not make a difference.

![record](https://user-images.githubusercontent.com/23088305/103182021-a9ad1c00-4875-11eb-8bcd-a94bd1931c3b.gif)
[Juice WRLD - Wishing Well.zip](https://github.com/jwallet/spy-spotify/files/5745448/Juice.WRLD.-.Wishing.Well.zip)

> I use a brilliant tool called VoiceMeeter
Voicemeeter is a more complex tool that has a UI too create a volume mixer for your device, behind it uses VirtualAudioCable. VirtualAudioCable is already included with Spytify, you can install it directly in Spytify Settings using the DeviceIcon next to AudioDevice line. Select this audio device and set Spotify to use this Output instead and you will be able to isolates both app.

All this info is already available in Spytify website in the FAQ. Click on [?] in the app to open the FAQ. See the section `Isolate Spotify audio to a different audio endpoint device. `

![image](https://user-images.githubusercontent.com/23088305/103182073-466fb980-4876-11eb-807a-31c26c84e3bd.png)

> As you know, Spytify needs the output to be in stereo. You do not have to change the output from your default audio device from multichannel to stereo and back anymore, if you normally use multichannel output (5.1, 6.1 or 7.1)!

You don't need to change your audio device anymore to record in stereo. Spytify includes a fallback to stereo if your channels are above 2 and has also a fallback for sample rate if it's over 48k.

![image](https://user-images.githubusercontent.com/23088305/103182122-e3325700-4876-11eb-8bfe-1e277df54686.png)

**Comment by R-W-C** [comment] 2020-12-28 13:58
Hi thanks. I am sure it will help others. The info about "Isolating Spotify audio to a different audio endpoint device." was that already there, or has this been added recently? I cannot remember I have read it before in the FAQ.

Let me take the opportunity to thank you for this really nice app. Cheers!

**Comment by jwallet** [comment] 2020-12-28 16:37
@R-W-C Thanks, and yes this section was already in the FAQ

**Comment by jwallet** [comment] 2020-12-28 22:12
I just found out some audio sound card are really poor quality, which will affect your recordings, I'm glad that mine is actually good enough for recordings;

I tested my pc and my lenovo laptop using a random song : michael bubble look a lot like xmas
I recorded using bitrate at 160kpbs and another try with 320kbps, the quality changed a bit but the main difference are the sound card, since it's an hardware issue, I can't do much to fix that

[michael-bubble-track-test-stereo-44k-sample-rate.zip](https://github.com/jwallet/spy-spotify/files/5748925/michael-bubble-track-test-stereo-44k-sample-rate.zip)

**Comment by jwallet** [comment] 2020-12-29 04:15
I updated the FAQ about that issue https://jwallet.github.io/spy-spotify/faq.html#install-better-audio-endpoint-device

**Comment by jwallet** [comment] 2020-12-31 05:02
I'm closing it since it is hardware related and the user has to follow the website section on [How to use it](https://jwallet.github.io/spy-spotify/overview.html#how-to-use-it) to avoid this issue with their system.

**Closed by jwallet** 2020-12-31 05:02 UTC
Labels: bug 🐞, hardware related 📻, workaround ♻
