### ISSUE TITLE
Track recorded on the same file as the precedent track

### ISSUE THREAD

**Issue by eros404** [jwallet/spy-spotify#435] opened 2022-09-10 12:43 UTC
Hi !

First really nice project.
My first recording sessions worked well.

But today I try to do another and as you can see Spytify record the first track well.
Then for the second track it will overwrite the audio of the first one.

Version: 1.10.1

In final for 2 tracks recorded I end with 1 file with the ID3 data of the first and the audio of the second.

![image](https://user-images.githubusercontent.com/69208964/189483865-4e9ce6c4-445c-457a-b1bd-37daff3ea11c.png)

**Edit**:
So I have downloaded again Spytify and the bug is not happening for now.

**Edit 2**:
It happened again :/

**Comment by Coca162** [comment] 2022-10-10 23:41
This seems to be happening when I move or add anything to a playlist

**Comment by eros404** [comment] 2022-10-11 08:21
It happens for me but i didn't move anything, just launched my playlist and wait.

**Comment by rikrak** [comment] 2022-10-11 08:35
@Coca162  I've just tried to record a playlist without changing anything, but this issue still occurred.  In my scenario the logs looked like this (spacing mine for clarity):
```
[08:36:34] Recording: Song 01

[08:39:29] Recording: Song 02
[08:39:32] Recorded: ..\Song 01.mp3 in 02:55

[08:43:41] Recording: Song 03
[08:43:46] Recorded: ..\Song 02.mp3 in 04:11

[08:46:46] Recording: Song 04
[08:46:49] Recorded: ..\Song 02.mp3 in 03:03        <--- Song 03 recorded with Song 02's details

[08:50:43] Recording: Song 05
[08:50:47] Recorded: ..\Song 04.mp3 in 03:56

[08:55:22] Recording: Song 06
[08:55:27] Recorded: ..\Song 05.mp3 in 04:38

[08:59:28] Recording: Song 07
[08:59:33] Recorded: ..\Song 06.mp3 in 04:05

[09:04:11] Recording: Song 08
[09:04:16] Recorded: ..\Song 06.mp3 in 04:41      <--- Song 07 recorded with Song 06's details

[09:08:39] Recording: Song 09
[09:08:44] Recorded: ..\Song 07.mp3 in 04:27      <--- Song 08 recorded with Song 07's details

[09:12:52] Recording: Song 10
[09:12:57] Recorded: ..\Song 09.mp3 in 04:11

[09:15:38] Recording: Song 11
[09:15:40] Recorded: ..\Song 09.mp3 in 02:45      <--- Song 10 recorded with Song 09's details
```

**Comment by rikrak** [comment] 2022-10-14 16:39
I've had a look into the code and I've narrowed down the cause of this.
The Track class has a [method that allows the Title to be set ](https://github.com/jwallet/spy-spotify/blob/702745bbbe49bee723f57ab9c404a72b25512665/EspionSpotify/Models/Track.cs#L126)once information has been taken from an API.  Additionally the [Title property on Track](https://github.com/jwallet/spy-spotify/blob/702745bbbe49bee723f57ab9c404a72b25512665/EspionSpotify/Models/Track.cs#L70) will return the _apiTitle in preference to the original title it had.  This essentially means the Title property can change its value at some point in its lifespan.

What appears to be happening is that when a new track is queued up, the previous track is written to disk.  This all happens at the same in an asynchronous manner.  A process goes off to discover the title for the new track from an API, but when it is set, it uses the title from the previous track.  

The track's Title property is used to form the file names, so this is where the problem begins.

I haven't spotted a solution, but at least I'm closer to the cause :-)

**Comment by jwallet** [comment] 2022-10-16 20:01
Are you guys using Spotify desktop app from spotify website (.exe file downloaded) or from the Windows Store? I did not have an issue like that and I'm using the app from Windows Store.

**Comment by rikrak** [comment] 2022-10-17 07:22
Ah!  I'm using a version built from the github code

**Comment by Coca162** [comment] 2022-10-18 18:46
After using Spytify for a bit more I do indeed have this issue even when not moving anything around.

Also @jwallet I am using the Spotify desktop app from the exe.

**Comment by eddwhite** [comment] 2022-10-19 10:46
I have also started encountering the same problem. I've been using release 1.10.1 for a while, and this only started happening recently. I've also noticed that this doesn't happen when using the LastFM API instead of the Spotify API

**Comment by rikrak** [comment] 2022-10-19 11:49
It could well be something that has changed at Spotify's side.  If the API takes a little longer to respond than previously it could have exposed a race condition in the existing code.

**Comment by jwallet** [comment] 2022-11-20 20:32
Anyone tried to record using Spotify from the Windows Store, I'm currently recording and I still have no problem, 23 tracks recorded so far, none missing. So I'm wondering if I using the .exe file from their website produces that bug. Of course while recording it's better to keep the windows session active and not lock your PC for example, Spytify will still record, but if I remember correctly Spotify won't provide track info if the window is not rendered at all (like the screen went to sleep). I'm thinking to add a caffeine feature to the app if that is the issue.

If someone will like to help out,  you can try one of the following "solution" to know if one of these fixes the bug;
- [ ] Record using Spotify from the Windows Store --- _probably not the solution if LastFM API works_
- [ ] Keep Spotify windows foreground while recording (not minimized in the tray)
- [ ] Use [caffeine app](https://www.zhornsoftware.co.uk/caffeine/) to prevent the computer to go to sleep (it simulates a keypress every minute)

**Comment by jwallet** [comment] 2022-11-25 21:50
did someone here tried the latest release? I would like to know if it resolved the issue

**Comment by rikrak** [comment] 2022-11-27 12:42
For info: I've update my fork of the code, re-built, and run a test today.  I'm not seeing the problem anymore :-)
(recorded a playlist of > 18 tracks)

**Comment by eddwhite** [comment] 2022-12-15 09:19
I've updated to the latest release (love the auto-update feature btw!) and I am no longer encountering this problem 🥳

**Comment by jwallet** [comment] 2023-01-07 00:29
i'm closing this issue then, thanks all for your feeback it's appreciated

**Closed by jwallet** 2023-01-07 00:29 UTC
Labels: bug 🐞
