### ISSUE TITLE
Crackling in Recording

### ISSUE THREAD

**Issue by TheERaichu** [jwallet/spy-spotify#113] opened 2019-09-05 22:05 UTC
**What is the bug ?**
> After recording a track I get crackling in the mp3 file.spot

**How to reproduce it or what's the expected behavior ?**
> Steps to reproduce the behavior or describe the expected behavior:

**Track used**
> Spotify track/playlist used : https://open.spotify.com/playlist/4g3mQ678yVSchVouoGZkHb

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by jwallet** [comment] 2019-09-05 22:52
duplicate of #102 
solution #103

**Closed** 2019-09-05 22:54 UTC
Labels: duplicate
