### ISSUE TITLE
When using Bluetooth headphones - HRESULT: 0x80070006 (E_HANDLE)

### ISSUE THREAD

**Issue by ner00** [jwallet/spy-spotify#369] opened 2021-07-12 23:47 UTC
**What is the bug ?**
> Program doesn't start
> Steps to reproduce the behavior or describe the expected behavior: Connect BT headphones and open Spytify v1.6~1.9

Reverted to v1.5 which seem to be working with the same setup.

v1.6 and above errors out when using BT headpones:
```
   at NAudio.CoreAudioApi.Interfaces.IAudioEndpointVolume.SetMasterVolumeLevelScalar(Single fLevel, Guid& pguidEventContext)
   at EspionSpotify.AudioSessions.MainAudioSession.SetAudioDeviceVolume(Int32 volume)
   at EspionSpotify.FrmEspionSpotify.TbVolumeWin_ValueChanged(Object sender, EventArgs e)
   at MetroFramework.Controls.MetroTrackBar.OnValueChanged()
   at MetroFramework.Controls.MetroTrackBar.set_Value(Int32 value)
   at EspionSpotify.FrmEspionSpotify.UpdateAudioEndPointFields(Int32 volume, String friendlyName)
   at EspionSpotify.FrmEspionSpotify.Init()
   at EspionSpotify.FrmEspionSpotify..ctor()
   at EspionSpotify.Program.Main()
```

**Comment by jwallet** [comment] 2021-07-24 12:47
sorry cannot reproduce, I tried: 
- bluetooth headphones
- bluetooth google home
- bluetooth monster speaker

without any errors, closing the issue.
the error you got comes from NAudio API which means this known library was not able to change your device volume, apprently not found. make sure it was connected properly, looks like it found no device at all, not even a default device.
reopen if you have more details.

**Closed by jwallet** 2021-07-24 12:47 UTC
Labels: bug 🐞, cannot reproduce ❌, hardware related 📻
