### ISSUE TITLE
problem when the counter 0999 it wont record

### ISSUE THREAD

**Issue by vipermetcaff** [jwallet/spy-spotify#262] opened 2020-09-30 18:39 UTC
![Untitled](https://user-images.githubusercontent.com/6171564/94725999-dbb3ee00-0319-11eb-8e49-1189a504ba15.png)

**Comment by jwallet** [comment] 2020-10-03 01:53
fixed in 1.Next #265 EspionSpotify/Watcher.cs

**Comment by vipermetcaff** [comment] 2020-10-05 22:48
[16:36:11] // Counter: Max file sequence prefix of 9999 reached
still  wont record past 0999

**Comment by jwallet** [comment] 2020-10-13 15:10
@vipermetcaff did you fork the repo and built and ran the solution. cause like I said it will be fix in the next release `1.Next`

**Comment by vipermetcaff** [comment] 2020-10-14 08:09
yes still not working for me

**Comment by jwallet** [comment] 2020-10-15 17:03
did you increment the mask input, it's normal to stop when it reaches `9999` if the mask is `0000`, otherwise it won't order properly all recorded tracks in order when burned to a cd.
```
0001_track
9999_track
10000_track // it will play before 9999_track
```
hold `CTRL` when clicking on `+` or `-` of the counter

**Comment by vipermetcaff** [comment] 2020-10-22 16:15
Yes
Here is a pic of whats its doing 
![image](https://user-images.githubusercontent.com/6171564/96900208-14de0a80-144f-11eb-8500-9c8885d9c375.png)

**Comment by jwallet** [comment] 2020-12-27 21:42
I tested it in release 1.8 and I cannot reproduce it anymore. Please feel free to reopen it if you still have the issue
![image](https://user-images.githubusercontent.com/23088305/103180289-757c3000-4862-11eb-904f-38f878d16ff9.png)

**Closed by jwallet** 2020-12-27 21:42 UTC
Labels: bug 🐞
